export enum EButtonStyleType {
  PRIMARY = 'PRIMARY',
  PRIMARY_TRANSPARENT = 'PRIMARY_TRANSPARENT',
  PRIMARY_TEXT = 'PRIMARY_TEXT',
  PRIMARY_OUTLINE = 'PRIMARY_OUTLINE',

  TRANSPARENT = 'TRANSPARENT',

  TAN_HIDE = 'TAN_HIDE',

  GRAY_OUTLINE = 'GRAY_OUTLINE',
}
