export enum EModalAuthType {
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  VERIFY_FORGOT_PASSWORD = 'VERIFY_FORGOT_PASSWORD',
  CHANGE_NEW_PASSWORD = 'CHANGE_NEW_PASSWORD',
  SUCCESS = 'SUCCESS',
}
