export enum EUIAction {
  SET_GEO_APP_LOCATION = 'SET_GEO_APP_LOCATION',
  SET_CART = 'SET_CART',
  SET_VISIBLE_OTHER_SHOP_WARNING = 'SET_VISIBLE_OTHER_SHOP_WARNING',
  RESET_ACTION_STATUS = 'RESET_ACTION_STATUS',
}
